// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: ssl_simulation_custom_erforce_robot_spec.proto

package simctl

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Custom robot specs for ER-Force simulator
type RobotSpecErForce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The distance [m] from the robot center to the ball, when the ball is as close as possible to the robot.
	// The ball may be a little bit inside the roboter when looking from top, due to the dimensions of the dribbler.
	ShootRadius *float32 `protobuf:"fixed32,1,opt,name=shoot_radius,json=shootRadius" json:"shoot_radius,omitempty"`
	// The height of the dribbling bar from the ground [m]
	DribblerHeight *float32 `protobuf:"fixed32,2,opt,name=dribbler_height,json=dribblerHeight" json:"dribbler_height,omitempty"`
}

func (x *RobotSpecErForce) Reset() {
	*x = RobotSpecErForce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssl_simulation_custom_erforce_robot_spec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RobotSpecErForce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotSpecErForce) ProtoMessage() {}

func (x *RobotSpecErForce) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_simulation_custom_erforce_robot_spec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotSpecErForce.ProtoReflect.Descriptor instead.
func (*RobotSpecErForce) Descriptor() ([]byte, []int) {
	return file_ssl_simulation_custom_erforce_robot_spec_proto_rawDescGZIP(), []int{0}
}

func (x *RobotSpecErForce) GetShootRadius() float32 {
	if x != nil && x.ShootRadius != nil {
		return *x.ShootRadius
	}
	return 0
}

func (x *RobotSpecErForce) GetDribblerHeight() float32 {
	if x != nil && x.DribblerHeight != nil {
		return *x.DribblerHeight
	}
	return 0
}

var File_ssl_simulation_custom_erforce_robot_spec_proto protoreflect.FileDescriptor

var file_ssl_simulation_custom_erforce_robot_spec_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x73, 0x73, 0x6c, 0x5f, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f,
	0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x5e, 0x0a, 0x10, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x53, 0x70, 0x65, 0x63, 0x45, 0x72, 0x46,
	0x6f, 0x72, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x5f, 0x72, 0x61,
	0x64, 0x69, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x6f,
	0x74, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x64, 0x72, 0x69, 0x62, 0x62,
	0x6c, 0x65, 0x72, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0e, 0x64, 0x72, 0x69, 0x62, 0x62, 0x6c, 0x65, 0x72, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52,
	0x6f, 0x62, 0x6f, 0x43, 0x75, 0x70, 0x2d, 0x53, 0x53, 0x4c, 0x2f, 0x73, 0x73, 0x6c, 0x2d, 0x73,
	0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x69,
	0x6d, 0x63, 0x74, 0x6c,
}

var (
	file_ssl_simulation_custom_erforce_robot_spec_proto_rawDescOnce sync.Once
	file_ssl_simulation_custom_erforce_robot_spec_proto_rawDescData = file_ssl_simulation_custom_erforce_robot_spec_proto_rawDesc
)

func file_ssl_simulation_custom_erforce_robot_spec_proto_rawDescGZIP() []byte {
	file_ssl_simulation_custom_erforce_robot_spec_proto_rawDescOnce.Do(func() {
		file_ssl_simulation_custom_erforce_robot_spec_proto_rawDescData = protoimpl.X.CompressGZIP(file_ssl_simulation_custom_erforce_robot_spec_proto_rawDescData)
	})
	return file_ssl_simulation_custom_erforce_robot_spec_proto_rawDescData
}

var file_ssl_simulation_custom_erforce_robot_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ssl_simulation_custom_erforce_robot_spec_proto_goTypes = []interface{}{
	(*RobotSpecErForce)(nil), // 0: RobotSpecErForce
}
var file_ssl_simulation_custom_erforce_robot_spec_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ssl_simulation_custom_erforce_robot_spec_proto_init() }
func file_ssl_simulation_custom_erforce_robot_spec_proto_init() {
	if File_ssl_simulation_custom_erforce_robot_spec_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ssl_simulation_custom_erforce_robot_spec_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RobotSpecErForce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ssl_simulation_custom_erforce_robot_spec_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ssl_simulation_custom_erforce_robot_spec_proto_goTypes,
		DependencyIndexes: file_ssl_simulation_custom_erforce_robot_spec_proto_depIdxs,
		MessageInfos:      file_ssl_simulation_custom_erforce_robot_spec_proto_msgTypes,
	}.Build()
	File_ssl_simulation_custom_erforce_robot_spec_proto = out.File
	file_ssl_simulation_custom_erforce_robot_spec_proto_rawDesc = nil
	file_ssl_simulation_custom_erforce_robot_spec_proto_goTypes = nil
	file_ssl_simulation_custom_erforce_robot_spec_proto_depIdxs = nil
}
