robot-specs:
  "TIGERs Mannheim":
    radius: 0.09
    height: 0.15
    mass: 2
    max_linear_kick_speed: 8
    max_chip_kick_speed: 8
    center_to_dribbler: 0.073
    limits:
      acc_speedup_absolute_max: 3
      acc_speedup_angular_max: 50
      acc_brake_absolute_max: 6
      acc_brake_angular_max: 50
      vel_absolute_max: 3
      vel_angular_max: 20
    custom_erforce:
      shoot_radius: 0.067
      dribbler_height: 0.04
      dribbler_width: 0.07
  "ER-Force":
    radius: 0.09
    height: 0.15
    mass: 2
    max_linear_kick_speed: 8
    max_chip_kick_speed: 8
    center_to_dribbler: 0.073
    limits:
      acc_speedup_absolute_max: 3
      acc_speedup_angular_max: 50
      acc_brake_absolute_max: 6
      acc_brake_angular_max: 50
      vel_absolute_max: 3
      vel_angular_max: 20
    custom_erforce:
      shoot_radius: 0.067
      dribbler_height: 0.04
      dribbler_width: 0.07
